drop schema if exists spotdb;
create schema spotdb;
use spotdb;

-- if tables exist do not create them
drop table if exists CUSTOMER;
drop table if exists LOT;
drop table if exists RESERVATION;
drop table if exists SPOT;
drop table if exists ORDERS;
drop table if exists VEHICLE;

CREATE TABLE CUSTOMER (
    EMAIL VARCHAR(40) NOT NULL,
    FNAME VARCHAR(25) NOT NULL,
    LNAME VARCHAR(25) NOT NULL,
    PWD VARCHAR(20) NOT NULL,
    LICENSE_NUM VARCHAR(16) NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE LOT (
	LOT_ID VARCHAR(4),
    LAT DECIMAL(4,2) NOT NULL,
    LNG DECIMAL(4,2) NOT NULL, 
    LOT_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (LOT_ID)
);

CREATE TABLE RESERVATION (
	RESERVATION_ID VARCHAR(4),
    LOT_ID VARCHAR(4) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
	PRIMARY KEY (RESERVATION_ID),
    FOREIGN KEY (LOT_ID) REFERENCES LOT(LOT_ID)
);

CREATE TABLE SPOT (
	SPOT_ID VARCHAR(4),
    LOT_ID VARCHAR(4),
    STD_AVAILABILITY MEDIUMINT NOT NULL,
    VIP_AVAILABILITY MEDIUMINT NOT NULL,
    STD_PRICE DECIMAL(4,2) NOT NULL,
    VIP_PRICE DECIMAL(4,2) NOT NULL,
	PRIMARY KEY (SPOT_ID),
    FOREIGN KEY (LOT_ID) REFERENCES LOT(LOT_ID)
);

CREATE TABLE ORDERS (
	ORDER_ID VARCHAR(4), 
    EMAIL VARCHAR(4) NOT NULL,
	RESERVATION_ID VARCHAR(4) NOT NULL,
	SPOT_ID VARCHAR(4) NOT NULL,
    PRICE DECIMAL(4,2),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (EMAIL) REFERENCES CUSTOMER(EMAIL),
    FOREIGN KEY (LOT_ID) REFERENCES LOT(LOT_ID),
    FOREIGN KEY (SPOT_ID) REFERENCES SPOT(SPOT_ID)
);

CREATE TABLE VEHICLE (
	VEHICLE_ID VARCHAR(4), 
    EMAIL VARCHAR(4) NOT NULL,
	MAKE VARCHAR(10) NOT NULL,
    MODEL VARCHAR(15) NOT NULL,
    V_YEAR VARCHAR(4) NOT NULL,
    COLOR VARCHAR(12) NOT NULL,
    LICENSE_PLATE VARCHAR(8) NOT NULL,
    PRIMARY KEY (VEHICLE_ID),
    FOREIGN KEY (EMAIL) REFERENCES CUSTOMER(EMAIL)
);
