SELECT R.RESERVATION_ID,R.START_TIME, L.LOT_NAME, L.LOT_ID, S.STD_AVAILABILITY
FROM reservation as R, spot as S, lot as l
WHERE S.R_DATE = "2021-05-16" AND S.SPOT_ID = R.SPOT_ID AND S.LOT_ID = "3" AND S.LOT_ID = L.LOT_ID;
