SELECT R.RESERVATION_ID,R.START_TIME, L.LOT_NAME, L.LOT_ID, S.STD_AVAILABILITY
FROM reservation as R, spot as S, lot as l
WHERE S.R_DATE = "2021-05-16" AND S.SPOT_ID = R.SPOT_ID AND S.LOT_ID = "3" AND S.LOT_ID = L.LOT_ID;

SELECT PARK_LOC FROM RESERVATION AS R, SPOT AS S WHERE S.LOT_ID = '2' AND S.SPOT_ID = R.SPOT_ID AND R.START_TIME = '18:00:00' AND S.R_DATE = "2021-05-15";
